# Generated by Django 4.2.7 on 2023-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_events_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='limit_clients',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='quantity_clients',
            field=models.SmallIntegerField(default=0),
        ),
    ]
