# Generated by Django 4.2.7 on 2023-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_events_limit_clients_events_quantity_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DateEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('event', models.ManyToManyField(related_name='date_event', to='organization.events')),
            ],
            options={
                'db_table': 'date_event',
            },
        ),
    ]
