# Generated by Django 4.2.7 on 2023-12-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_eventrecords_delete_dateevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='limit_clients',
        ),
        migrations.RemoveField(
            model_name='events',
            name='quantity_clients',
        ),
        migrations.AddField(
            model_name='eventrecords',
            name='limit_clients',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecords',
            name='quantity_clients',
            field=models.SmallIntegerField(default=0),
        ),
    ]
