# Generated by Django 4.2.7 on 2023-12-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_recordings'),
        ('organization', '0006_remove_events_limit_clients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRecords',
        ),
    ]
