# Generated by Django 4.2.7 on 2023-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_records_events_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='record',
            field=models.ManyToManyField(related_name='events', to='organization.records'),
        ),
    ]
