# Generated by Django 4.2.7 on 2024-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_events_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='recordings',
            field=models.ManyToManyField(related_name='records', to='customer.recordings'),
        ),
    ]
