# Generated by Django 4.2.7 on 2024-01-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_records_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='recordings',
        ),
    ]
