# Generated by Django 4.2.7 on 2024-01-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_remove_events_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='events',
            field=models.ForeignKey(default=135, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='organization.events'),
            preserve_default=False,
        ),
    ]
