# Generated by Django 4.2.7 on 2024-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_records_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
