# Generated by Django 4.2.7 on 2024-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_events_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='events',
            name='status_tariff',
            field=models.CharField(choices=[('paid', 'платный'), ('free', 'бесплатный')], default='paid', max_length=4),
            preserve_default=False,
        ),
    ]
