# Generated by Django 4.2.7 on 2024-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_events_options_events_status_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizations',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='records',
            name='status_opening',
            field=models.CharField(choices=[('open', 'открытый'), ('close', 'закрытый')], default='open', max_length=10),
        ),
    ]
