# Generated by Django 4.2.7 on 2023-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categories_organizations_categories_check_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(error_messages={'unique': 'такая организация уже зарегистрирована'}, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
