# Generated by Django 4.2.7 on 2023-12-07 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organizations_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('employees', models.ManyToManyField(related_name='events', to='core.employees', verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AlterField(
            model_name='organizations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.categories', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_recording', models.CharField(choices=[('paid', 'оплачено'), ('canc', 'отменено')], max_length=4, verbose_name='Статус записи')),
                ('date_recording', models.DateTimeField(auto_now=True, verbose_name='Дата записи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organizations', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='employees',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.organizations'),
        ),
        migrations.AddConstraint(
            model_name='recordings',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_recordings_user'),
        ),
    ]
