# Generated by Django 4.2.7 on 2023-12-08 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employees_events_alter_organizations_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'клиент'), ('organization', 'организация')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(blank=True, error_messages={'unique': 'такая организация уже зарегистрирована'}, max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(blank=True, max_length=250, verbose_name='увлечения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
