# Generated by Django 4.2.7 on 2023-12-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_customer_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='events',
            name='organization',
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('sport', 'спорт'), ('tourism', 'туризм'), ('education', 'образование'), ('science', 'наука'), ('entertainment', 'развлечение'), ('sundry', 'разное')], default='sundry', max_length=50),
        ),
    ]
