# Generated by Django 4.2.7 on 2023-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employees_user_alter_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'клиент'), ('organization', 'организация')], default='customer', max_length=20),
        ),
    ]
