# Generated by Django 4.2.7 on 2023-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='if_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
