# Generated by Django 4.2.7 on 2023-12-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_role_user_if_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_organization',
            new_name='is_organization',
        ),
    ]
