# Generated by Django 4.2.7 on 2023-12-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_organization_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='user',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
    ]
