# Generated by Django 4.2.7 on 2023-12-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_organizations_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordings',
            name='event',
        ),
        migrations.RemoveField(
            model_name='recordings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Recordings',
        ),
    ]
