# Generated by Django 4.2.7 on 2023-12-17 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_events_is_active_dateevents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_recording', models.CharField(choices=[('paid', 'оплачено'), ('canc', 'отменено')], max_length=4, verbose_name='Статус записи')),
                ('date_recording', models.DateTimeField(auto_now=True, verbose_name='Дата записи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='organization.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.AddConstraint(
            model_name='recordings',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_recordings_user'),
        ),
    ]
