# Generated by Django 4.2.7 on 2023-12-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_recordings_event_recordings_event_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recordings',
        ),
    ]
