# Generated by Django 4.2.7 on 2023-12-29 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0009_alter_events_record'),
        ('customer', '0003_delete_recordings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_recording', models.CharField(choices=[('paid', 'оплачено'), ('canc', 'отменено')], max_length=4, verbose_name='Статус записи')),
                ('date_recording', models.DateTimeField(auto_now=True, verbose_name='Дата записи')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='organization.records', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.AddConstraint(
            model_name='recordings',
            constraint=models.UniqueConstraint(fields=('record', 'user'), name='unique_recordings_user'),
        ),
    ]
