# Generated by Django 4.2.7 on 2024-01-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordings',
            name='record',
        ),
    ]
