# Generated by Django 4.2.7 on 2024-01-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_recordings_record'),
    ]


