# Generated by Django 4.2.7 on 2024-01-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recordings',
            constraint=models.UniqueConstraint(fields=('record', 'user'), name='unique_recordings_user'),
        ),
    ]
